import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Urbanist } from 'next/font/google';
import './globals.css';
import Footer from '@/components/Footer';

const urbanist = Urbanist({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
  preload: true,
  fallback: ['sans-serif'],
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'ResuAI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={urbanist.className}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen  antialiased bg-white dark:bg-gray-950 p-6`}
      >
        <main className="flex-grow">
          <div
            aria-hidden="true"
            className="absolute inset-0 grid grid-cols-2 -space-x-52 opacity-40 dark:opacity-20"
          >
            <div className="blur-[106px] h-56 bg-gradient-to-br from-primary to-purple-400 dark:from-blue-400"></div>
            <div className="blur-[106px] h-32 bg-gradient-to-r from-cyan-400 to-sky-300 dark:to-indigo-300"></div>
          </div>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
